#Requires -Version 5.1
# Generated by ROCmRoll - do not edit manually
# Instance: {InstanceName}
# Channel : {Channel}
# Created : {CreatedAt}

param(
    [Parameter(Mandatory = $false, ValueFromPipeline = $false)]
    [string]$ProfileArg = '',
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ExtraArgs = @()
)

$ErrorActionPreference = 'Stop'

try {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding = [System.Text.Encoding]::UTF8
} catch { }

$RootFolder        = '{RootFolder}'
$SharedFolder      = '{SharedFolder}'
$InstanceFolder    = '{InstanceFolder}'
$EnvironmentFolder = '{EnvironmentFolder}'
$PythonExe         = Join-Path $EnvironmentFolder 'python.exe'
$LogsFolder        = Join-Path $RootFolder 'logs\launch'
$SitePackagesFolder = Join-Path $EnvironmentFolder 'Lib\site-packages'
$RocmSdkCoreFolder  = Join-Path $SitePackagesFolder '_rocm_sdk_core'
$RocmSdkDevelFolder = Join-Path $SitePackagesFolder '_rocm_sdk_devel'
$TritonCacheFolder  = Join-Path $RootFolder '.cache\triton'
$TunableOpCacheFolder = Join-Path $RootFolder '.cache\tunableop'

# ---------------------------------------------------------------------------
# Fixed process-local environment - isolation only, never persisted globally
# ---------------------------------------------------------------------------
$env:PYTHONHOME              = ''
$env:PYTHONPATH              = $InstanceFolder
$env:PIP_CACHE_DIR           = Join-Path $RootFolder '.cache\pip'
$env:PIP_DISABLE_PIP_VERSION_CHECK = '1'
$env:PIP_NO_INPUT            = '1'
$env:PIP_REQUIRE_VIRTUALENV  = 'false'
$env:TRITON_CACHE_DIR        = $TritonCacheFolder
$env:PYTORCH_TUNABLEOP_CACHE_DIR = $TunableOpCacheFolder

# ---------------------------------------------------------------------------
# ROCm/HIP infrastructure
# ---------------------------------------------------------------------------
$env:HIP_VISIBLE_DEVICES = '0'

# rocm_sdk's offload-arch GPU discovery spawns an unquoted exe path and breaks
# on space-containing install paths; pre-seed the target family detected at
# install time, but only when this distribution actually ships it (stable
# direct-URL wheels ship a single 'custom' family and self-resolve, and an
# unavailable value makes rocm_sdk raise ValueError on torch import).
# Profiles load later and can override this value.
$RocmTargetFamily = '{RocmIndex}'
if ($RocmTargetFamily -and -not $env:ROCM_SDK_TARGET_FAMILY) {
    $PrevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $FamiliesJson = & $PythonExe -c 'import json; from rocm_sdk import _dist_info; print(json.dumps(list(_dist_info.AVAILABLE_TARGET_FAMILIES)))' 2>$null
        # [string[]] cast: PS 5.1's ConvertFrom-Json returns JSON arrays as a single
        # array object, which @() would wrap instead of enumerate.
        $Families = [string[]](($FamiliesJson | Out-String).Trim() | ConvertFrom-Json)
        if ($Families -contains $RocmTargetFamily) {
            $env:ROCM_SDK_TARGET_FAMILY = $RocmTargetFamily
        }
    } catch { } finally {
        $ErrorActionPreference = $PrevEap
    }
}

$PathEntries = @(
    $EnvironmentFolder,
    (Join-Path $EnvironmentFolder 'Scripts'),
    (Join-Path $RocmSdkDevelFolder 'bin'),
    (Join-Path $RocmSdkCoreFolder 'bin')
) | Where-Object { $_ -and (Test-Path $_) }
if ($PathEntries.Count -gt 0) {
    $env:PATH = (($PathEntries + @($env:PATH)) -join ';')
}

$RocmSdkExe = Join-Path $EnvironmentFolder 'Scripts\rocm-sdk.exe'
if (Test-Path $RocmSdkExe) {
    & $RocmSdkExe init *> $null
    $sdkRoot = (& $RocmSdkExe path --root 2>$null | Select-Object -First 1)
    if ($sdkRoot -and (Test-Path $sdkRoot)) {
        $env:ROCM_HOME = $sdkRoot
        $env:HIP_PATH  = $sdkRoot
        $env:ROCM_PATH = $sdkRoot
    }
}

if (-not $env:ROCM_HOME) {
    if (Test-Path $RocmSdkDevelFolder) {
        $env:ROCM_HOME = $RocmSdkDevelFolder
        $env:HIP_PATH  = $RocmSdkDevelFolder
        $env:ROCM_PATH = $RocmSdkDevelFolder
    } elseif (Test-Path $RocmSdkCoreFolder) {
        $env:ROCM_HOME = $RocmSdkCoreFolder
        $env:HIP_PATH  = $RocmSdkCoreFolder
        $env:ROCM_PATH = $RocmSdkCoreFolder
    }
}

$HsaOverrideGfxVersion = '{GfxVersion}'
if ($HsaOverrideGfxVersion -match '^\d+\.\d+\.\d+$') {
    $env:HSA_OVERRIDE_GFX_VERSION = $HsaOverrideGfxVersion
} else {
    Remove-Item Env:\HSA_OVERRIDE_GFX_VERSION -ErrorAction SilentlyContinue
}

$IsLegacyGpu = $HsaOverrideGfxVersion -match '^(?i:gfx101X|gfx103X)$'

if ($HsaOverrideGfxVersion -ine 'gfx1100' -and (Test-Path $RocmSdkDevelFolder)) {
    $env:MIOPEN_SYSTEM_DB_PATH   = Join-Path $RocmSdkDevelFolder 'bin'
    $env:ROCBLAS_TENSILE_DB_PATH = Join-Path $RocmSdkDevelFolder 'bin\rocblas'
    $env:ROCBLAS_TENSILE_LIBPATH = Join-Path $RocmSdkDevelFolder 'bin\rocblas\library'
}

# ---------------------------------------------------------------------------
# Profile loading
# ---------------------------------------------------------------------------
$ProfilesFolder = '{ProfilesFolder}'
$ActiveProfile  = if ($ProfileArg) { $ProfileArg } else { '{ProfileName}' }
$ProfileJson    = Join-Path $ProfilesFolder "$ActiveProfile.json"
$LoadedProfile  = $null

if (Test-Path $ProfileJson) {
    try {
        $LoadedProfile = Get-Content $ProfileJson -Raw | ConvertFrom-Json
    } catch {
        Write-Warning "Failed to load profile '$ActiveProfile': $_. Using no extra configuration."
    }
} else {
    Write-Warning "Profile '$ActiveProfile' not found at '$ProfileJson'. Using no extra configuration."
}

# Apply profile env vars (after ROCm infrastructure so profile can override)
if ($LoadedProfile -and $LoadedProfile.env) {
    foreach ($kv in $LoadedProfile.env.PSObject.Properties) {
        Set-Item "Env:\$($kv.Name)" $kv.Value
    }
}

# Apply legacy GPU specific overrides from profile (or fallback hardcoded)
if ($IsLegacyGpu) {
    if ($LoadedProfile -and $LoadedProfile.legacyGpuOverrides -and $LoadedProfile.legacyGpuOverrides.env) {
        foreach ($kv in $LoadedProfile.legacyGpuOverrides.env.PSObject.Properties) {
            Set-Item "Env:\$($kv.Name)" $kv.Value
        }
    } else {
        $env:TORCH_BACKENDS_CUDA_FLASH_SDP_ENABLED   = '0'
        $env:TORCH_BACKENDS_CUDA_MEM_EFF_SDP_ENABLED = '0'
        $env:TORCH_BACKENDS_CUDA_MATH_SDP_ENABLED    = '1'
    }
} else {
    $env:TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL = '1'
}

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
$LogFile = Join-Path $LogsFolder ("{0}_{1}_launch.log" -f (Get-Date -Format 'yyyy-MM-dd'), '{InstanceName}')
if (-not (Test-Path $LogsFolder)) { New-Item -ItemType Directory -Path $LogsFolder -Force | Out-Null }
if (-not (Test-Path $TritonCacheFolder)) { New-Item -ItemType Directory -Path $TritonCacheFolder -Force | Out-Null }
if (-not (Test-Path $TunableOpCacheFolder)) { New-Item -ItemType Directory -Path $TunableOpCacheFolder -Force | Out-Null }

Write-Host "Launching ComfyUI instance: {InstanceName}  [profile: $ActiveProfile]" -ForegroundColor Cyan
Write-Host "Environment : $EnvironmentFolder"
Write-Host "Log         : $LogFile"

function ConvertTo-PlainLaunchLogLine {
    param([AllowNull()][string]$Line)

    if ($null -eq $Line) { return '' }

    $plain = [string]$Line
    $esc = [regex]::Escape([string][char]27)

    # Strip terminal control sequences only for the persisted log.
    $plain = [regex]::Replace($plain, ('{0}\][^\x07]*(?:\x07|{0}\\)' -f $esc), '')
    $plain = [regex]::Replace($plain, ('{0}\[[0-?]*[ -/]*[@-~]' -f $esc), '')
    $plain = [regex]::Replace($plain, ('{0}.' -f $esc), '')
    return [regex]::Replace($plain, '[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]', '')
}

# ---------------------------------------------------------------------------
# Launch arguments
# ---------------------------------------------------------------------------
$LaunchArgs = @(
    '--listen', '127.0.0.1',
    '--port', '{Port}',
    '--extra-model-paths-config', "$InstanceFolder\extra_model_paths.yaml",
    #'--user-directory', "$SharedFolder\user",
    '--input-directory',  "$SharedFolder\input",
    '--output-directory', "$SharedFolder\output",
    '--temp-directory',   "$SharedFolder\temp"
)

# Append profile launch args
if ($LoadedProfile -and $LoadedProfile.launchArgs -and $LoadedProfile.launchArgs.Count -gt 0) {
    $LaunchArgs += $LoadedProfile.launchArgs
}

# Append legacy GPU launch args from profile
if ($IsLegacyGpu) {
    if ($LoadedProfile -and $LoadedProfile.legacyGpuOverrides -and $LoadedProfile.legacyGpuOverrides.launchArgs) {
        $LaunchArgs += $LoadedProfile.legacyGpuOverrides.launchArgs
    }
}

if ($ExtraArgs.Count -gt 0) {
    $LaunchArgs += $ExtraArgs
}

$Bootstrap = @"
import os
import runpy
import sys

instance = r'''$InstanceFolder'''
main_py = os.path.join(instance, 'main.py')
if instance not in sys.path:
    sys.path.insert(0, instance)
sys.argv = [main_py] + sys.argv[1:]
runpy.run_path(main_py, run_name='__main__')
"@

$PythonArgs = @('-c', $Bootstrap) + $LaunchArgs

$exitCode = 0
Push-Location $InstanceFolder
try {
    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $writer = $null
    try {
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        $writer = [System.IO.StreamWriter]::new($LogFile, $true, $utf8NoBom)
        & $PythonExe $PythonArgs *>&1 | ForEach-Object {
            $line = if ($_ -is [System.Management.Automation.ErrorRecord]) { $_.Exception.Message } else { [string]$_ }
            Write-Host $line
            $writer.WriteLine((ConvertTo-PlainLaunchLogLine -Line $line))
        }
        $exitCode = $LASTEXITCODE
    } finally {
        if ($writer) { $writer.Flush(); $writer.Close(); $writer.Dispose() }
        $ErrorActionPreference = $previousErrorActionPreference
    }
} finally {
    Pop-Location
}
exit $exitCode
